# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/ecat_tb/ecat_tb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb || ORIG_REF_NAME==ecat_tb} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_processing_system7_0_0/ecat_tb_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_processing_system7_0_0 || ORIG_REF_NAME==ecat_tb_processing_system7_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_axi_gpio_0_0/ecat_tb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_axi_gpio_0_0 || ORIG_REF_NAME==ecat_tb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_xbar_1/ecat_tb_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_xbar_1 || ORIG_REF_NAME==ecat_tb_xbar_1} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_ps7_0_axi_periph_0/ecat_tb_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_ps7_0_axi_periph_0 || ORIG_REF_NAME==ecat_tb_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_rst_ps7_0_25M_0/ecat_tb_rst_ps7_0_25M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_rst_ps7_0_25M_0 || ORIG_REF_NAME==ecat_tb_rst_ps7_0_25M_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_ecat_top_0_0/ecat_tb_ecat_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_ecat_top_0_0 || ORIG_REF_NAME==ecat_tb_ecat_top_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_clk_wiz_0_0/ecat_tb_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_clk_wiz_0_0 || ORIG_REF_NAME==ecat_tb_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_proc_sys_reset_0_0/ecat_tb_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_proc_sys_reset_0_0 || ORIG_REF_NAME==ecat_tb_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_axi_ethernetlite_0_0/ecat_tb_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_axi_ethernetlite_0_0 || ORIG_REF_NAME==ecat_tb_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_xlconstant_0_0/ecat_tb_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_xlconstant_0_0 || ORIG_REF_NAME==ecat_tb_xlconstant_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_xlconstant_1_0/ecat_tb_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_xlconstant_1_0 || ORIG_REF_NAME==ecat_tb_xlconstant_1_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_apb_bridge_0_0/ecat_tb_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_apb_bridge_0_0 || ORIG_REF_NAME==ecat_tb_apb_bridge_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_axi_apb_bridge_0_0/ecat_tb_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_axi_apb_bridge_0_0 || ORIG_REF_NAME==ecat_tb_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_axi_protocol_convert_0_1/ecat_tb_axi_protocol_convert_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_axi_protocol_convert_0_1 || ORIG_REF_NAME==ecat_tb_axi_protocol_convert_0_1} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_ila_0_0/ecat_tb_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_ila_0_0 || ORIG_REF_NAME==ecat_tb_ila_0_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_auto_pc_2/ecat_tb_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_auto_pc_2 || ORIG_REF_NAME==ecat_tb_auto_pc_2} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_auto_pc_0/ecat_tb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_auto_pc_0 || ORIG_REF_NAME==ecat_tb_auto_pc_0} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_auto_pc_1/ecat_tb_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_auto_pc_1 || ORIG_REF_NAME==ecat_tb_auto_pc_1} -quiet] -quiet

# IP: bd/ecat_tb/ip/ecat_tb_auto_cc_0/ecat_tb_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ecat_tb_auto_cc_0 || ORIG_REF_NAME==ecat_tb_auto_cc_0} -quiet] -quiet

# XDC: bd/ecat_tb/ecat_tb_ooc.xdc
