# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/mii_ila_1_0.xci
# IP: The module: 'mii_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/mii_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/mii_ila_1_0.xci
# IP: The module: 'mii_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_ila_1_0/mii_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
