# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1.xci
# IP: The module: 'mii_rst_ps7_0_25M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_rst_ps7_0_25M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_rst_ps7_0_25M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_rst_ps7_0_25M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1.xci
# IP: The module: 'mii_rst_ps7_0_25M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_rst_ps7_0_25M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_rst_ps7_0_25M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_rst_ps7_0_25M_1/mii_rst_ps7_0_25M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_rst_ps7_0_25M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
