# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_axi_apb_bridge_0_0/mii_axi_apb_bridge_0_0.xci
# IP: The module: 'mii_axi_apb_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_axi_apb_bridge_0_0/mii_axi_apb_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_axi_apb_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_axi_apb_bridge_0_0/mii_axi_apb_bridge_0_0.xci
# IP: The module: 'mii_axi_apb_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpgawork/mmi/mmi.srcs/sources_1/bd/mii/ip/mii_axi_apb_bridge_0_0/mii_axi_apb_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mii_axi_apb_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
